### ISSUE TITLE
Process pending after warning/error message on" invalid SDFs detected"

### ISSUE THREAD

**Issue by lfnothias** [TomasVrzal/DeepReI#3]
Hi,
Thanks for your work and sharing the code and model ! 
I was able to run DeepReI (after a pretty convulated installation process) and I ran it successfully on 5k SMILES. It took about 5 minutes on my machine.
Now I am trying to scale it up to 50k SMILES but it looks like it is stalling. Basically the process is pending after the following warning/error but the "DeepReI in progress" keeps spinning. From the activity monitor, neither the CPU and GPU are being used like it was for the 5k SMILES, and I let it flow for 2 days without any change. Does that mean the process is dead because of some incorrect SMILES entries ?
```
==============================
*** Open Babel Warning  in ParseComplex
  Illegal aromatic element te
Warning in read.SDFset(unlist(strsplit(defs, "\n", fixed = TRUE))) :
  5 invalid SDFs detected. To fix, run: valid <- validSDF(sdfset); sdfset <- sdfset[valid]
Warning: Error in [: subscript out of bounds
  [No stack trace available]
```

**Comment by TomasVrzal** [comment]
Hi,
Thanks for your interest in our DeepReI model.
Based on the warning, it looks like there are 5 unusual SMILE strings in your dataset - ChemmineR and/or ChemmineOB package is not able to process the SMILE and put it forward to the DeepReI model.
Please check it by validSDF function.

**Comment by lfnothias** [comment]
Hi Tomas, thanks a lot for the quick response. That makes sense. 
I have very limited knowledge of R, but it seems this documentation [should help me figuring it out](https://www.bioconductor.org/packages/devel/bioc/vignettes/ChemmineR/inst/doc/ChemmineR.html#Import_of_Compounds). 
Essentially, with ChemmineR -> import the SMILES -> convert to SDF objects -> and then apply the validSDF function. 

I believe it would be a nice extra feature for DeepReI to have the string of "incorrect" SMILES reported in the R console log, and even better if they could also be ignored.

**Comment by lfnothias** [comment]
It seems relevant: https://github.com/EuracBiomedicalResearch/CompoundDb/issues/69

**Comment by lfnothias** [comment]
Can you advise with this ? I am following that procedure for SMILES import with ChemmineR: `https://bioconductor.org/packages/devel/bioc/vignettes/ChemmineR/inst/doc/ChemmineR.html#SMILES_Import`

But I can't get more than 100 compounds imported, even when doing `> options(chemminer.max.upload = 150000)`

**Comment by TomasVrzal** [comment]
I am not really sure what is wrong with your SMILES import with Chemminer (the dataset from the instruction contains only 100 molecules). Did you try it with your own (larger) dataset? I have no problem with the import, I check it with 17413 molecules and all of them were imported.

Regarding your suggestion to add an extra feature for DeepReI: We are planning to extend the DeepReI with the polar and standard non-polar stationary phase, together with some functionality improvement (e.g. ignoring of incorrect SMILES).

**Comment by lfnothias** [comment]
Super cool for the upcoming additional stationary phases and functionalities 👍 

Thanks a lot ! It is fixed. It turns out that I inadvertently rewrote the file to 100 smiles :)
